include:
  - ./ui/docker-compose.yaml
  - ./llama-cpp-server.${LLM_DEVICE_TYPE:-cpu}.docker-compose.yaml
  - ./python/fastfoodordering/docker-compose.yaml
  - ./parser/OmniParserFork/browser-image-parser.${PARSER_MODE:-disabled}.docker-compose.yaml

services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 10000:8080

networks:
  default:
    name: ${DOCKER_NETWORK_NAME:-fast-food}
