# Base parameters
MODEL_PATH: mradermacher/UI-TARS-1.5-7B-GGUF # String path to GGUF model
MODEL_ARGS: # Dictionary of arguments to pass for model instantiation
  filename: UI-TARS-1.5-7B.Q4_K_M.gguf
  local_dir: ./models
  n_gpu_layers: -1
  n_ctx: 2048
# Vision parameters
VISION_HANDLER_TYPE: MiniCPMv26ChatHandler # String representing class of ChatHandler
VISION_HANDLER_PATH: mradermacher/UI-TARS-1.5-7B-GGUF # String path to GGUF CLIP-like model
VISION_ARGS:
  local_dir: ./models
  filename: UI-TARS-1.5-7B.mmproj-f16.gguf
