services:
  session-manager:
    container_name: session-manager
    build:
      context: .
      dockerfile: core/session/Dockerfile
    env_file:
      - ../../.env
    environment:
      - OPENAI_BASE_URL=http://host.docker.internal:8000
      - DOCKER_HOST=unix:///var/run/docker.sock
      - BROWSER_VISIBILITY_MODE=default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    extra_hosts:
      - host.docker.internal:host-gateway
