FROM mcr.microsoft.com/playwright:v1.36.0-focal

# sudo apt-get update
# sudo apt-get install -y \
#    libvpx6 \
#    libicu66 \
#    libwoff1 \
#    libjpeg62-turbo \
#    libgstreamer1.0-0 \
#    libgstreamer-plugins-base1.0-0

# npx playwright install-deps
