services:
  session-manager:
    container_name: session-manager
    build:
      context: .
      dockerfile: core/session/Dockerfile
    command: ["uv", "run", "session_manager"]
    env_file:
      - ../../.env
    ports:
      - 8080:8080
