services:
  fastfoodordering-ui:
    container_name: fastfoodordering-ui
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ../.env
    ports:
      - "3001:3000"
      # - "24678:24678"  # HMR port
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    # environment:
    #   - CHOKIDAR_USEPOLLING=true

  coqui-tts:
    container_name: coqui-tts
    build:
      context: ./coqui_service
      dockerfile: Dockerfile
    ports:
      - "5055:5055"
    volumes:
      - ~/.local/share/tts:/root/.local/share/tts
    restart: unless-stopped
